### ISSUE TITLE
Cloudfare doesn't allow access

### ISSUE THREAD

**Issue by maximka1** [Cryptorubic/rubic_frontend#25]
Cloudfare forbids users from entering platform at rubic.exchange. 

There's no captcha to differentiate between users and bots. Some users are mistakenly considered bots, therefore disallowing them from using the platform and there's no way for a user to prove he's human without captcha. 

Suggested solution: update Cloudfare protection settings to allow captcha.

**Comment by siandreev** [comment]
We have added some of Datacenters' IP addresses that have participated at the DDOS attack last month at the forbidden list and they are banished immediately. We have no plans to implement captcha as we already have differentiation between users and bots.

**Comment by maximka1** [comment]
Well that sucks. Because I'm no bot, havent' participated in and DDoS
attacks, but Cloudfare doesn't allow me to access your platform. That's
just dumb to be honest, not to implement second check on human vs bot via
captcha. Most projects do it to let the users in and bots out.
